AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Kinesis Data Firehose delivery stream'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for Firehose delivery
    Default: poc2-data-analytics-kt
  
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Lambda function for data transformation
    Default: ''

  FirehoseRoleArn:
    Type: String
    Description: ARN of the Firehose IAM role from IAM stack

Resources:
  FirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub 'data-delivery-stream-${Environment}'
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub 'arn:aws:s3:::${S3BucketName}'
        RoleARN: !Ref FirehoseRoleArn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CompressionFormat: UNCOMPRESSED
        Prefix: 'data/'
        ErrorOutputPrefix: 'error/'
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !Ref LambdaFunctionArn

Outputs:
  FirehoseDeliveryStreamName:
    Description: Name of the Kinesis Data Firehose delivery stream
    Value: !Ref FirehoseDeliveryStream
    Export:
      Name: !Sub '${AWS::StackName}-FirehoseDeliveryStreamName'
  
  FirehoseDeliveryStreamArn:
    Description: ARN of the Kinesis Data Firehose delivery stream
    Value: !GetAtt FirehoseDeliveryStream.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FirehoseDeliveryStreamArn'
  
