AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating a simple S3 bucket in us-east-1 for data analytics POC'

Parameters:
  FirehoseRoleArn:
    Type: String
    Description: ARN of the IAM role for Kinesis Firehose delivery stream

Resources:
  DataAnalyticsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'poc2-data-analytics-kt'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: 'ClickstreamDataLifecycle'
            Status: Enabled
            Filter:
              Prefix: 'data/'
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
            ExpirationInDays: 2555  # 7 years retention for analytics data
          - Id: 'ErrorDataLifecycle'
            Status: Enabled
            Filter:
              Prefix: 'error/'
            Transitions:
              - TransitionInDays: 7
                StorageClass: STANDARD_IA
              - TransitionInDays: 30
                StorageClass: GLACIER
            ExpirationInDays: 90  # Shorter retention for error data
          - Id: 'AthenaResultsLifecycle'
            Status: Enabled
            Filter:
              Prefix: 'athena-results/'
            Transitions:
              - TransitionInDays: 7
                StorageClass: STANDARD_IA
            ExpirationInDays: 30  # Short retention for query results
          - Id: 'IncompleteMultipartUploads'
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Project
          Value: POC-2-Data-Analytics
        - Key: ManagedBy
          Value: CloudFormation
        - Key: CostOptimized
          Value: 'true'

  DataAnalyticsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataAnalyticsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: 'PolicyID'
        Statement:
          - Sid: 'StmtID'
            Effect: 'Allow'
            Principal:
              AWS: !Ref FirehoseRoleArn
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
              - 's3:PutObjectAcl'
            Resource:
              - !GetAtt DataAnalyticsBucket.Arn
              - !Sub '${DataAnalyticsBucket.Arn}/*'

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref DataAnalyticsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt DataAnalyticsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
