AWSTemplateFormatVersion: '2010-09-09'
Description: 'Test S3 Bucket Creation'

Parameters:
  BackupBucketName:
    Type: String
    Description: Name of the S3 bucket for backups
    Default: kaldun-backup-test

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BackupBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the test bucket
    Value: !Ref TestBucket