AWSTemplateFormatVersion: '2010-09-09'
Description: 'Disaster Recovery POC - CloudWatch Monitoring'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  BackupBucketName:
    Type: String
    Description: Name of the backup S3 bucket
  
  UserEmail:
    Type: String
    Description: Email address for backup notifications
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  
  CostThresholdUSD:
    Type: Number
    Default: 50
    Description: Monthly cost threshold for alerts (USD)
    MinValue: 1
    MaxValue: 1000

Resources:
  # SNS Topic for backup notifications
  BackupNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'disaster-recovery-notifications-${Environment}'
      DisplayName: 'Disaster Recovery Backup Notifications'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Email subscription for notifications
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BackupNotificationTopic
      Protocol: email
      Endpoint: !Ref UserEmail

  # CloudWatch Log Group for backup operations
  BackupOperationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/disaster-recovery/backup-operations-${Environment}'
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: BackupOperations

  # CloudWatch Log Group for restore operations
  RestoreOperationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/disaster-recovery/restore-operations-${Environment}'
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: RestoreOperations

  # Custom metric filter for backup success
  BackupSuccessMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref BackupOperationsLogGroup
      FilterPattern: '[timestamp, level="SUCCESS", message="Backup completed successfully"]'
      MetricTransformations:
        - MetricNamespace: 'DisasterRecovery/Backup'
          MetricName: 'SuccessfulBackups'
          MetricValue: '1'
          DefaultValue: 0

  # Custom metric filter for backup failures
  BackupFailureMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref BackupOperationsLogGroup
      FilterPattern: '[timestamp, level="ERROR", ...]'
      MetricTransformations:
        - MetricNamespace: 'DisasterRecovery/Backup'
          MetricName: 'FailedBackups'
          MetricValue: '1'
          DefaultValue: 0

  # Custom metric filter for backup size
  BackupSizeMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref BackupOperationsLogGroup
      FilterPattern: '[timestamp, level="INFO", message="Backup size:", size_bytes]'
      MetricTransformations:
        - MetricNamespace: 'DisasterRecovery/Backup'
          MetricName: 'BackupSizeBytes'
          MetricValue: '$size_bytes'
          DefaultValue: 0

  # Custom metric filter for backup duration
  BackupDurationMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref BackupOperationsLogGroup
      FilterPattern: '[timestamp, level="INFO", message="Backup duration:", duration_seconds]'
      MetricTransformations:
        - MetricNamespace: 'DisasterRecovery/Backup'
          MetricName: 'BackupDurationSeconds'
          MetricValue: '$duration_seconds'
          DefaultValue: 0

  # CloudWatch Alarm for backup failures (updated to use custom metrics)
  BackupFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'DisasterRecovery-${Environment}-BackupFailures'
      AlarmDescription: 'Alerts when backup operations fail'
      MetricName: 'FailedBackups'
      Namespace: 'DisasterRecovery/Backup'
      Statistic: Sum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref BackupNotificationTopic
      TreatMissingData: notBreaching

  # CloudWatch Alarm for missing backups (no successful backups in 48 hours)
  MissingBackupAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'DisasterRecovery-${Environment}-MissingBackups'
      AlarmDescription: 'Alerts when no successful backups occur for 48 hours'
      MetricName: 'SuccessfulBackups'
      Namespace: 'DisasterRecovery/Backup'
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 2  # 2 periods = 48 hours
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref BackupNotificationTopic
      TreatMissingData: breaching

  # CloudWatch Alarm for high backup costs
  HighCostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'DisasterRecovery-${Environment}-HighCosts'
      AlarmDescription: !Sub 'Alerts when monthly costs exceed $${CostThresholdUSD}'
      MetricName: 'EstimatedCharges'
      Namespace: 'AWS/Billing'
      Statistic: Maximum
      Period: 86400  # 1 day
      EvaluationPeriods: 1
      Threshold: !Ref CostThresholdUSD
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Currency
          Value: USD
        - Name: ServiceName
          Value: AmazonS3
      AlarmActions:
        - !Ref BackupNotificationTopic
      TreatMissingData: notBreaching

  # CloudWatch Alarm for long backup duration
  LongBackupDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'DisasterRecovery-${Environment}-LongBackupDuration'
      AlarmDescription: 'Alerts when backup takes longer than 2 hours'
      MetricName: 'BackupDurationSeconds'
      Namespace: 'DisasterRecovery/Backup'
      Statistic: Maximum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 7200  # 2 hours in seconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref BackupNotificationTopic
      TreatMissingData: notBreaching

  # CloudWatch Dashboard for backup monitoring
  BackupDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'DisasterRecovery-${Environment}-Dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "BucketSizeBytes", "BucketName", "${BackupBucketName}", "StorageType", "DeepArchiveStorage" ],
                  [ "...", "StandardStorage" ],
                  [ "...", "StandardIAStorage" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Backup Storage Usage",
                "period": 86400,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "NumberOfObjects", "BucketName", "${BackupBucketName}", "StorageType", "AllStorageTypes" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Number of Backup Files",
                "period": 86400,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "AllRequests", "BucketName", "${BackupBucketName}" ],
                  [ ".", "PutRequests", ".", "." ],
                  [ ".", "GetRequests", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "S3 API Requests",
                "period": 3600
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "DisasterRecovery/Backup", "SuccessfulBackups" ],
                  [ ".", "FailedBackups" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Backup Success/Failure Rate",
                "period": 3600,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "DisasterRecovery/Backup", "BackupSizeBytes" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Backup Size Over Time",
                "period": 86400,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "DisasterRecovery/Backup", "BackupDurationSeconds" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Backup Duration",
                "period": 86400,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 18,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/disaster-recovery/backup-operations-${Environment}'\n| fields @timestamp, level, message\n| filter level = \"SUCCESS\" or level = \"ERROR\"\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Backup Operations",
                "view": "table"
              }
            }
          ]
        }

  # CloudWatch Log Group for backup operations
  BackupOperationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/disaster-recovery/backup-operations-${Environment}'
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Log Group for restore operations
  RestoreOperationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/disaster-recovery/restore-operations-${Environment}'
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Insights queries for backup analysis
  BackupInsightsQuery:
    Type: AWS::Logs::QueryDefinition
    Properties:
      Name: !Sub 'DisasterRecovery-${Environment}-BackupSummary'
      LogGroupNames:
        - !Ref BackupOperationsLogGroup
      QueryString: |
        fields @timestamp, operation, status, file_count, total_size_mb
        | filter operation = "backup"
        | stats count() as backup_count, 
                sum(file_count) as total_files, 
                sum(total_size_mb) as total_size_mb by bin(5m)
        | sort @timestamp desc

  RestoreInsightsQuery:
    Type: AWS::Logs::QueryDefinition
    Properties:
      Name: !Sub 'DisasterRecovery-${Environment}-RestoreSummary'
      LogGroupNames:
        - !Ref RestoreOperationsLogGroup
      QueryString: |
        fields @timestamp, operation, status, job_id, restore_type
        | filter operation = "restore"
        | stats count() as restore_count by status, restore_type
        | sort @timestamp desc

Outputs:
  NotificationTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !Ref BackupNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopicArn'
  
  BackupLogGroupName:
    Description: Name of the backup operations log group
    Value: !Ref BackupOperationsLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-BackupLogGroupName'
  
  RestoreLogGroupName:
    Description: Name of the restore operations log group
    Value: !Ref RestoreOperationsLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-RestoreLogGroupName'
  
  DashboardURL:
    Description: URL of the CloudWatch dashboard
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${BackupDashboard}'
    Export:
      Name: !Sub '${AWS::StackName}-DashboardURL'