AWSTemplateFormatVersion: '2010-09-09'
Description: 'Disaster Recovery POC - Main Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  BackupBucketName:
    Type: String
    Description: Name of the S3 bucket for backups (must be globally unique)
    AllowedPattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
    ConstraintDescription: 'Bucket name must be lowercase, contain only letters, numbers, and hyphens'
  
  UserEmail:
    Type: String
    Description: Email address for backup notifications
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  
  RetentionYears:
    Type: Number
    Default: 7
    Description: Number of years to retain backups
    MinValue: 1
    MaxValue: 10
  
  CostThresholdUSD:
    Type: Number
    Default: 50
    Description: Monthly cost threshold for alerts (USD)
    MinValue: 1
    MaxValue: 1000
  
  EnableCrossRegionReplication:
    Type: String
    Default: 'false'
    Description: Enable cross-region replication for disaster recovery
    AllowedValues:
      - 'true'
      - 'false'
  
  ReplicationRegion:
    Type: String
    Default: 'us-west-2'
    Description: Target region for cross-region replication (if enabled)
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-southeast-1
      - ap-northeast-1

Resources:
  # IAM Stack - Deploy first to create user and roles
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yaml
      Parameters:
        Environment: !Ref Environment
        BackupBucketName: !Ref BackupBucketName
      TimeoutInMinutes: 10

  # S3 Stack - Deploy after IAM to reference user ARN
  S3Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
    Properties:
      TemplateURL: ./s3.yaml
      Parameters:
        Environment: !Ref Environment
        BackupBucketName: !Ref BackupBucketName
        RetentionYears: !Ref RetentionYears
        BackupUserArn: !GetAtt IAMStack.Outputs.BackupUserArn
        EnableCrossRegionReplication: !Ref EnableCrossRegionReplication
        ReplicationRegion: !Ref ReplicationRegion
      TimeoutInMinutes: 15

  # CloudWatch Stack - Deploy last for monitoring
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3Stack
      - IAMStack
    Properties:
      TemplateURL: ./cloudwatch.yaml
      Parameters:
        Environment: !Ref Environment
        BackupBucketName: !Ref BackupBucketName
        UserEmail: !Ref UserEmail
        CostThresholdUSD: !Ref CostThresholdUSD
      TimeoutInMinutes: 10

Outputs:
  # Infrastructure Information
  BackupBucketName:
    Description: Name of the backup S3 bucket
    Value: !GetAtt S3Stack.Outputs.BucketName
  
  BackupBucketArn:
    Description: ARN of the backup S3 bucket
    Value: !GetAtt S3Stack.Outputs.BucketArn
  
  # IAM Credentials (Handle securely)
  BackupUserName:
    Description: Name of the IAM user for backup operations
    Value: !GetAtt IAMStack.Outputs.BackupUserName
  
  AccessKeyId:
    Description: Access Key ID for the backup user
    Value: !GetAtt IAMStack.Outputs.AccessKeyId
  
  # SecretAccessKey removed for security - retrieve directly from IAM if needed
  # Use: aws iam list-access-keys --user-name <username> to get key ID
  # Then: aws configure set aws_secret_access_key <secret> --profile backup-user
  
  # Monitoring Resources
  NotificationTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !GetAtt CloudWatchStack.Outputs.NotificationTopicArn
  
  DashboardURL:
    Description: URL of the CloudWatch dashboard
    Value: !GetAtt CloudWatchStack.Outputs.DashboardURL
  
  # Log Groups
  BackupLogGroupName:
    Description: Name of the backup operations log group
    Value: !GetAtt CloudWatchStack.Outputs.BackupLogGroupName
  
  RestoreLogGroupName:
    Description: Name of the restore operations log group
    Value: !GetAtt CloudWatchStack.Outputs.RestoreLogGroupName
  
  # Configuration Summary
  DeploymentSummary:
    Description: Summary of deployed resources
    Value: !Sub |
      Disaster Recovery Infrastructure Deployed Successfully
      
      Environment: ${Environment}
      Backup Bucket: ${BackupBucketName}
      Retention Period: ${RetentionYears} years
      Cost Alert Threshold: $${CostThresholdUSD} USD/month
      Notification Email: ${UserEmail}
      
      Next Steps:
      1. Configure AWS CLI with the provided credentials
      2. Download and configure backup scripts
      3. Run initial backup test
      4. Set up backup scheduling
      
      Dashboard: ${CloudWatchStack.Outputs.DashboardURL}